# Generated by Django 5.0.14 on 2025-08-19 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'action'), name='unique_user_product_action'),
        ),
    ]
